### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by jsbjx** [avollkopf/cbpi4-BM_Steps#1]
BM_MashInStep:
Heats up to the target temp and stops when temp is reached. This can be used to add e.g. Malt Pipe. User has to manually move to next step
   Can you add an option. Don’t send notifications and keep warm. Automatic next step, which is useful for multi-step saccharification.

**Comment by avollkopf** [comment]
As mentioned in the FB group, I have currently time constraints and will focus on fixing issues with the existing software. This Plugin is also just an example on how one can create a plugin. Currently, I have no plans to modify/add any features due to the aforementioned resaons. I need to focus on the server and the PWM actors and afterwards on the kettle logic.

**Comment by jsbjx** [comment]
Thank you for your answer, the current environment needs to achieve multiple saccharification. It can only be achieved by pressing confirmation at each step. No automatic process can be achieved. The question with me should involve many users, you are a programmer. It will be perfect if there are prompts or the option to go directly to the next step.

**Comment by avollkopf** [comment]
I am not sure what you really need. The steps that are now nativley included allow for full automated brewing. Only the mashin step requires a confirmation as you need to add malt to your kettle once the water has reached the temperature. However, you don't need to use this step as first step. For a full msahing process, you should use the mash step and not a sequence of mashin steps. https://openbrewing.gitbook.io/craftbeerpi4_support/master/craftbeerpi-4-server/mash-profile

**Comment by jsbjx** [comment]
The saccharification process is divided into 38 °-52 °-68 ° temperature range, but for the first time you need to prompt to add wheat. Others do not need to be reminded, I hope to run automatically, this is my purpose.

**Comment by avollkopf** [comment]
No you don't need this. Please read the documentation carefully. You don't need to use the mashin step as first step. Just use a mash step as first step.

**Comment by jsbjx** [comment]
I read the document carefully. The example is the monocular mode. Mine is a three-barrel structure. I use PID-HERMS plug-in to basically solve the problem I encountered, thank you!

PID-HERMS plugin
Internal Loop: Seconds of the internal loop -> Determines maximum PID resolution
How to determine this parameter? What is the value range? What does the value affect?

**Comment by avollkopf** [comment]
Well, then we are not talking about a step to control your HLT or some other kettle but a kettle logic. Cbpi4 can‘t run two mash steps in parallel to control two kettles je.g. Masthun and HLT). I consider this issue as closed. The other plugin will change in a few weeks and this parameter will become obsolete. Logic will be simplified.
